Encoding:
  Enabled: False
LineLength:
  Max: 600
Documentation:
  Enabled: False
SpaceBeforeFirstArg:
  Enabled: false
AsciiComments:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
